# Generated by Django 5.2.15 on 2026-06-21 16:34

import apps.notices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=apps.notices.models.SecureFilePath('notices/'), validators=[apps.notices.models.validate_file_size]),
        ),
    ]
