# Generated by Django 5.2.15 on 2026-06-21 16:34

import apps.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=apps.events.models.SecureFilePath('events_templates/'), validators=[apps.events.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.events.models.SecureFilePath('mentors_photos/'), validators=[apps.events.models.validate_file_size]),
        ),
    ]
