# Generated by Django 5.2.15 on 2026-08-06 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_available_seats_event_category_event_end_time_and_more'),
        ('tenure', '0004_alter_member_options_alter_tenure_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tenure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tenure.tenure'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Select an existing team member, or leave blank for guest/external mentors.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_profiles', to='tenure.member'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
