# Generated by Django 6.0 on 2026-06-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='events_templates/'),
        ),
    ]
