# Generated by Django 5.2.15 on 2026-06-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cms_user', 'Cms User')], default='cms_user', max_length=20),
        ),
    ]
