# Generated by Django 5.2.15 on 2026-06-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
