# Generated by Django 5.2.15 on 2026-06-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
