# Generated by Django 5.2.15 on 2026-08-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificate_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_project_completed',
            field=models.BooleanField(default=True),
        ),
    ]
