# Generated by Django 6.0 on 2026-06-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notice_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(blank=True, choices=[('administrative', 'Administrative'), ('academic', 'Academic'), ('events', 'Events')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='notices/'),
        ),
    ]
