# Generated by Django 5.2.15 on 2026-06-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
