# Generated by Django 5.2.15 on 2026-07-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_pastpaper_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastpaper',
            old_name='subject_code',
            new_name='subject_name',
        ),
        migrations.AlterModelOptions(
            name='pastpaper',
            options={'ordering': ['-exam_year', '-semester', 'subject_name']},
        ),
        migrations.AlterUniqueTogether(
            name='pastpaper',
            unique_together={('subject_name', 'semester', 'exam_year')},
        ),
    ]
