# Generated by Django 5.2.15 on 2026-07-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_alter_pastpaper_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='subject_name',
            field=models.CharField(choices=[('CSC114', 'Introduction to Information Technology'), ('CSC115', 'C Programming'), ('CSC116', 'Digital Logic'), ('MTH117', 'Mathematics I'), ('PHY118', 'Physics'), ('CSC165', 'Discrete Structures'), ('CSC166', 'Object Oriented Programming (C++)'), ('CSC167', 'Microprocessor'), ('MTH168', 'Mathematics II'), ('STA169', 'Statistics I'), ('CSC211', 'Data Structures and Algorithms'), ('CSC212', 'Numerical Methods'), ('CSC213', 'Computer Architecture'), ('CSC214', 'Computer Graphics'), ('STA215', 'Statistics II'), ('CSC262', 'Theory of Computation'), ('CSC263', 'Computer Networks'), ('CSC264', 'Operating Systems'), ('CSC265', 'Database Management System'), ('CSC266', 'Artificial Intelligence'), ('CSC325', 'Design and Analysis of Algorithms'), ('CSC326', 'System Analysis and Design'), ('CSC327', 'Cryptography'), ('CSC328', 'Simulation and Modeling'), ('CSC329', 'Web Technology'), ('CSC330', 'Multimedia Computing'), ('CSC331', 'Wireless Networking'), ('CSC332', 'Image Processing'), ('CSC333', 'Knowledge Management'), ('CSC334', 'Society and Ethics in IT'), ('CSC335', 'Microprocessor Based Design'), ('CSC375', 'Software Engineering'), ('CSC376', 'Compiler Design and Construction'), ('CSC377', 'E-Governance'), ('CSC378', 'Net Centric Computing'), ('CSC379', 'Technical Writing'), ('CSC425', 'Advanced Java Programming'), ('CSC426', 'Data Warehousing and Data Mining'), ('MGT427', 'Principles of Management'), ('CSC428', 'Project I'), ('CSC429', 'Elective I'), ('CSC475', 'Advanced Database Management'), ('CSC476', 'Internship'), ('CSC477', 'Advanced Networking with IPv6'), ('CSC478', 'Decision Support Systems / Expert Systems'), ('CSC479', 'Elective II')], max_length=10, null=True),
        ),
    ]
