# Generated by Django 6.0 on 2026-06-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper',
            name='drive_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
