# Generated by Django 5.2.15 on 2026-06-21 16:34

import apps.tenure.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tenure.models.SecureFilePath('member_images/'), validators=[apps.tenure.models.validate_file_size]),
        ),
    ]
