# Generated by Django 5.2.15 on 2026-08-04 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenure', '0002_alter_member_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='tenure',
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to='tenure.member')),
                ('tenures', models.ManyToManyField(related_name='alumni', to='tenure.tenure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenureMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_type', models.CharField(choices=[('MEMBER', 'Member'), ('ADVISOR', 'Advisor')], default='MEMBER', max_length=20)),
                ('designation', models.CharField(help_text='e.g. Senior Advisor', max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenure.member')),
                ('tenure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenure.tenure')),
            ],
            options={
                'unique_together': {('member', 'tenure', 'role_type')},
            },
        ),
    ]
