# Generated by Django 5.2.15 on 2026-08-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenure', '0003_remove_member_tenure_alumni_tenuremembership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tenure',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='tenuremembership',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='tenuremembership',
            unique_together={('member', 'tenure')},
        ),
        migrations.RemoveField(
            model_name='member',
            name='role',
        ),
        migrations.AddField(
            model_name='tenuremembership',
            name='order',
            field=models.PositiveIntegerField(default=99, help_text='Order of hierarchy: 1=President, 2=Vice President, 3=Secretary, etc.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenuremembership',
            name='designation',
            field=models.CharField(help_text='e.g. President, Vice President, Treasurer', max_length=100),
        ),
        migrations.AlterField(
            model_name='tenuremembership',
            name='role_type',
            field=models.CharField(choices=[('EXECUTIVE', 'Executive Board'), ('ADVISOR', 'Advisor')], default='EXECUTIVE', max_length=20),
        ),
    ]
