# Generated by Django 5.2.15 on 2026-08-24 18:09

import apps.tenure.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenure', '0004_alter_member_options_alter_tenure_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tenure.models.SecureFilePath('member_signatures/'), validators=[apps.tenure.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='tenure',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tenure.models.SecureFilePath('president_signatures/'), validators=[apps.tenure.models.validate_file_size]),
        ),
    ]
