# Generated by Django 5.2.15 on 2026-08-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenure', '0005_member_signature_tenure_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='signature',
        ),
    ]
